# -*- coding: utf-8 -*-
"""Exercise3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W8w40oFhT8FsacoxblC2003WeGVnCC3H

what this program is doing
"""

x = 10
y = 1

if x > y:
  print("x is greater than y")
elif x == y:
  print("both are equal")
else:
  print("y is greater than x")