# -*- coding: utf-8 -*-
"""Exercise11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bVib3nXK3_Ox5Rky-uhe94WgjxBnsUBK

Write a regex code to find phone number from a pragraph as per your contry
"""