# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1naAtECvxR4JyJvKsrl0JpLdzEVPUtEm4

Write for loop till 10
"""



"""write while loop till 10"""

