# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FmHUuOYt-OCBDcVE32WQFX-DHfGhG4dr

Make variable and enter your name and print it out!
"""



"""Make variable and enter your age and print it out!"""



"""Make 2 variable and do multiplycation"""



"""Make 2 variable and do addition"""



"""Make 2 variable and do substaction"""



"""Make 2 variable and do division"""



"""Write all types of data types I taught you

Cut your name into 2 and do string concatenation
"""

