# -*- coding: utf-8 -*-
"""Exercise12.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eKx5Pk8ky00Eg9JdIpiAlxZ3Q--SofWp

Write an code for employee and his\her salary
"""

