# -*- coding: utf-8 -*-
"""Exercise1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hIgsZSW3gDuTCSDI09pfZRNfRxt_gXFQ

print hello world
"""



"""print any integer"""



"""Write meaning of string

Write meaning of integer
"""