# -*- coding: utf-8 -*-
"""Exercise6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iKs8dvW3KJac1lQap2dYuAbOEUA0NzsR

Make a dictionary
"""

