# -*- coding: utf-8 -*-
"""Exercise5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TN_8RS5f9Ykm8QALL1BXhhURQg8SWWm2

Write a list ofcitrus fruits
"""

