# -*- coding: utf-8 -*-
"""Exercise8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yvx2EbLSlFCPgNoi3K3rzVAiGN_Tz6ST

Write something about moduals and packages
"""