# -*- coding: utf-8 -*-
"""Exercise9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A7JWkv8cV5XQMdnh4IzByv4sqMt997OL

open a file here
"""

