# -*- coding: utf-8 -*-
"""Exercise10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SRpqKFVUcyG_9-SGRFvgpXALqEF03TsC
"""

# Write a exception handling code here.